services:
  hadoop:
    build: .
    container_name: hadoop-container
    hostname: hadoop
    ports:
      - "9870:9870"   # Namenode Web UI
      - "8088:8088"   # ResourceManager Web UI
      - "8042:8042"   # NodeManager Web UI
      - "9864:9864"   # DataNode Web UI
      - "9000:9000"   # HDFS Service
      - "19888:19888" # JobHistory Web UI
    volumes:
      - ./hadoop-data:/data     # For persistent HDFS data
      - ./input:/input   # Local input directory
      - ./output:/output # Local output directory
      - ./code:/code       # For Java/Python code
      - ./hadoop-configs:/usr/local/hadoop/etc/hadoop  # Custom configs
      - ./hadoop-logs:/opt/hadoop/logs # Hadoop logs
    environment:
      - HADOOP_HOME=/opt/hadoop
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-arm64
      - HADOOP_LOG_DIR=/opt/hadoop/logs
    mem_limit: 4g
    networks:
      - hadoop-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://hadoop:9870"]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  hadoop-data:
    driver: local
  hadoop-logs:
    driver: local

networks:
  hadoop-net:
    driver: bridge
